#!/bin/sh

cd `dirname $0`

if [ $# -lt 1 ];
then
echo "Usage: calculateClosure <pool_name> <args CalculateClosure>"
exit;
fi

export IBIS_OPTS="-Dibis.server.address=fs0:8111 -Dibis.pool.name=$1"
shift;

./launch.sh reasoner.CalculateClosure $*