#!/bin/bash
case X$1 in
    X)
	line=`grep "won election" ns.out | tail -1`
	pool=`expr "$line" : '.*pool "\(.*\)".*'`
	;;
    *)
	pool=$1
	;;
esac

echo computing closure with cluster running as pool $pool:

./query $pool --rules --closure
