#!/bin/bash

cd `dirname $0`

. ./init-env.sh

case X$1 in
    X)
	line=`grep "won election" ns.out | tail -1`
	pool=`expr "$line" : '.*pool "\(.*\)".*'`
	;;
    *)
	pool=$1
	;;
esac

export IBIS_OPTS="-Dibis.server.address=localhost:8011 -Dibis.pool.name=$pool"

java $JAVA_OPTS $IBIS_OPTS nl.vu.cs.querypie.Query --qsq $*
